version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: '@angular/*'
        versions:
          - '>= 0'
      - dependency-name: '@angular-devkit/*'
        versions:
          - '>= 0'
      - dependency-name: '@nrwl/*'
        versions:
          - '>= 0'
      - dependency-name: '@types/*'
        versions:
          - '>= 0'
      - dependency-name: 'core-js'
        versions:
          - '>= 0'
      - dependency-name: 'ts-jest'
        versions:
          - '>= 0'
      - dependency-name: 'cypress'
        versions:
          - '>= 0'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/functions'
    schedule:
      interval: daily
    ignore:
      - dependency-name: 'axios'
        versions:
          - '>= 0'
