name: test cloud functions

on:
  workflow_dispatch:
  push:
    paths:
      - 'firestore.rules'
      - 'functions/**'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    env:
      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache npm
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: ./functions/node_modules
          key: ${{ runner.os }}-node14-functions-${{ hashFiles('**/functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node14-functions-
      - name: Cache firebase emulators
        id: firebase-emulators-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.FIREBASE_EMULATORS_PATH }}
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('emulator-cache/**') }}
        continue-on-error: true
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test Application
        run: npm run test:ci
