name: test cloud functions

on:
  push:
    paths:
      - 'firestore.rules'
      - 'functions/**'
    branches:
      - trunk
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: install firebase-tools
        run: npm i -g firebase-tools
      - name: Test Application
        run: npm run test:ci
