name: Deploy Service

on:
  workflow_dispatch:
    inputs:
      repository:
        default: 'enroll'
        description: 'GitHub repository name'
        required: true
      service:
        default: 'enroll'
        description: The service to deploy
        required: true
      ref:
        default: 'trunk'
        description: The reference to deploy, could be a branch, tag or commit hash
        required: true
      environment:
        default: 'pvt3'
        description: Target environment for deployment
        required: true

jobs:
  deploy-service:
    runs-on: ubuntu-latest
    env:
      APP: ${{ github.event.inputs.service }}
      REF: ${{ github.event.inputs.ref }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      ORG: 'maine'
      REPO: ${{ github.event.inputs.repository }}
      USER: ${{ github.actor }}
    steps:
      - uses: actions/checkout@v2
        id: checkoutStep
        with:
          repository: 'ideacrew/${{ github.event.inputs.repository }}'
          ref: ${{ github.event.inputs.ref }}
      - name: Set commit sha to env variable
        run: echo "COMMIT_SHA=$(git log -n 1 --pretty=format:'%H')" >> $GITHUB_ENV
      - name: Post to Yellr
        run: |
          curl -L -X POST 'https://yellr.app/api/service-deployment' \
          -H 'Content-Type: application/json' \
          -d '{
              "app": "${{ env.APP }}",
              "branch": "${{ env.REF }}",
              "commit_sha": "${{ env.COMMIT_SHA }}",
              "env": "${{ env.ENVIRONMENT }}",
              "org": "${{ env.ORG }}",
              "repo": "${{ env.REPO }}",
              "status": "started",
              "user_name": "${{ env.USER }}"
          }'
        # id: yellrStart
        # uses: fjogeleit/http-request-action@master
        # with:
        #   url: 'https://yellr.app/api/service-deployment'
        #   method: POST
        #   data: >-
        #     {
        #       "app": "${{ env.APP }}",
        #       "branch": "${{ env.REF }}",
        #       "commit_sha": "${{ env.COMMIT_SHA }}",
        #       "env": "${{ env.ENVIRONMENT }}",
        #       "org": "${{ env.ORG }}",
        #       "repo": "${{ env.REPO }}"
        #       "status": "started"
        #       "user_name": "${{ env.USER }}"
        #     }
      - name: Do some deployment stuff
        run: |
          echo "Deploying $APP to $ENVIRONMENT"
          echo "Ref: $REF"
          echo "Commit SHA: ${{ env.COMMIT_SHA }}"
          echo "Deployment started by $USER"
