name: test and deploy front end

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - 'firestore.rules'
      - 'apps/**'
      - 'libs/**'
      - 'firebase.json'
      - 'package-lock.json'
      - 'package.json'
    branches:
      - trunk
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint Application
        run: npm run affected:lint
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Test Application
        run: npm run test
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build Application
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dashboard
          path: dist/apps/dashboard
  deploy:
    name: deploy
    environment: production
    needs: [lint, test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: dashboard
          path: dist/apps/dashboard
      - name: Deploy Application(s)
        if: success()
        run: npm run deploy:dashboard -- --token ${{ secrets.FIREBASE_TOKEN }}
      - name: print log
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: firebase-log
          path: /home/runner/.npm/_logs
